#spring
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:~/barogo
    driver-class-name: org.h2.Driver
    username: sa
    password:

#server
server:
  port: 8080

#MyBatis
mybatis:
  config-location: classpath:mybatis-configuration.xml
  mapper-locations: classpath:mappers/**/*.xml

# JWT
token:
  secret: barogo