create table member
(
    pk bigint generated by default as identity,
    id varchar(255),
    name varchar(255),
    password varchar(255),
    primary key (pk)
);

INSERT INTO member(id, name, password) VALUES ('test@test.com', 'test', '123test!');