DROP TABLE IF EXISTS MEMBER;

CREATE TABLE MEMBER
(
    pk bigint generated by default as identity,
    id varchar(255),
    name varchar(255),
    password varchar(255),
    primary key (pk)
);

DROP TABLE IF EXISTS "ORDER";

CREATE TABLE "ORDER"
(
    pk bigint generated by default as identity,
    member_pk bigint,
    order_at datetime,
    delivery_at datetime,
    delivery_address varchar(255),
    delivery_status varchar(255),
    total_price int,
    primary key (pk)
);

DROP TABLE IF EXISTS ORDER_ITEM;

CREATE TABLE ORDER_ITEM
(
    pk bigint generated by default as identity,
    order_pk bigint,
    item_pk bigint,
    quantity int,
    primary key (pk)
);

DROP TABLE IF EXISTS ITEM;

CREATE TABLE ITEM
(
    pk bigint generated by default as identity,
    agency_pk bigint,
    name varchar(255),
    price int,
    primary key (pk)
);

DROP TABLE IF EXISTS AGENCY;

CREATE TABLE AGENCY
(
    pk bigint generated by default as identity,
    name varchar(255),
    address varchar(255),
    primary key (pk)
);

DROP TABLE IF EXISTS COMMON_CODE;

CREATE TABLE COMMON_CODE
(
    pk bigint generated by default as identity,
    code_div varchar(255),
    code_key varchar(255),
    code_val varchar(255),
    primary key (pk)
);